create database customer_behaviour;
use customer_behaviour;

SELECT * FROM customer_behaviour_data;
SELECT AVG(PURCHASE_AMOUNT) FROM customer_behaviour_data;
RENAME TABLE customer_behaviour TO CUSTOMER_BEHAVIOUR_DATA;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER, SUM(PURCHASE_AMOUNT) AS REVENUE 
FROM customer_behaviour_DATA
GROUP BY GENDER;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT * FROM CUSTOMER_BEHAVIOUR_DATA
WHERE DISCOUNT_APPLIED = 'Yes' AND PURCHASE_AMOUNT > (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER_BEHAVIOUR_DATA);


-- Q3. Which are the top 5 products with the highest average review rating?
Select ITEM_PURCHASED, ROUND(AVG(REVIEW_RATING),2) AS AVG_REVIEW 
FROM CUSTOMER_BEHAVIOUR_DATA
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC
LIMIT 5;


SELECT COUNT(SHIPPING_TYPE), SHIPPING_TYPE FROM customer_behaviour_DATA
GROUP BY SHIPPING_TYPE
ORDER BY COUNT(SHIPPING_TYPE) DESC;

-- Q4. Compare the average purchase amounts between Standard and Free Shipping.
SELECT SHIPPING_TYPE, AVG(PURCHASE_AMOUNT) AS AVG_PURCHASE
FROM customer_behaviour_DATA
WHERE SHIPPING_TYPE IN ('FREE SHIPPING','STANDARD')
GROUP BY SHIPPING_TYPE;


-- Q5. Do subscribed customers spend more?
    -- Compare average spend and total revenue between subscribers and non-subscribers.
    
SELECT * FROM customer_behaviour_DATA;
    
SELECT AVG(PURCHASE_AMOUNT) AS AOV, SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE, SUBSCRIPTION_STATUS
FROM customer_behaviour_DATA
group by SUBSCRIPTION_STATUS;

-- Conclusion subscribed customers contribute less revenue than unsubscribed customers, even though AOV remanining same, 
-- that means subscribed customers by products that are low in value.

-- SUBSCRIPTION ANALYSIS
SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'YES';
SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'NO';

SELECT ((SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'YES')/count(CUSTOMER_ID)) * 100 AS PERCENT_OF_SUBSCRIBERS FROM customer_behaviour_DATA;

SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'NO' AND GENDER = 'MALE'
UNION
SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'NO' AND GENDER = 'FEMALE';

SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'YES' AND GENDER = 'MALE'
UNION
SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE SUBSCRIPTION_STATUS = 'YES' AND GENDER = 'FEMALE';


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT ITEM_PURCHASED, 100 * ROUND(SUM(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END)/ COUNT(*),2) AS DISCOUNT_RATE, COUNT(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END)
FROM customer_behaviour_DATA
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC
LIMIT 5;

-- LEAST percentage of purchases with discounts applied?
SELECT ITEM_PURCHASED, 100 * ROUND(SUM(CASE WHEN DISCOUNT_APPLIED = 'YES' THEN 1 ELSE 0 END)/ COUNT(*),2) AS DISCOUNT_RATE, COUNT(*)
FROM customer_behaviour_DATA
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE ASC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
    -- and show the count of each segment.
    
SELECT * FROM customer_behaviour_DATA;

UPDATE customer_behaviour_DATA 
SET PURCHASE_FREQUENCY_DAYS = 90
WHERE FREQUENCY_OF_PURCHASES = 'EVERY 3 MONTHS';


SELECT DISTINCT(FREQUENCY_OF_PURCHASES)
FROM customer_behaviour_DATA;

SELECT DISTINCT(PURCHASE_FREQUENCY_DAYS)
FROM customer_behaviour_DATA;

-- We would define returning customers to ones who had made a purchase between 2 and 15
-- And New customers would be defined as the ones who had made only 1 previous_purchases
WITH CUSTOMER_TYPE AS(
SELECT CUSTOMER_ID, PREVIOUS_PURCHASES, case
			 when previous_purchases between 2 and 15 THEN 'Returning customers'
             when previous_purchases = 1 THEN 'New customers' ELSE 'Loyal' END AS CUSTOMER_SEGMENT from customer_behaviour_data)

SELECT CUSTOMER_SEGMENT, COUNT(*) AS Number_of_customers
from customer_type
group by customer_segment;

SELECT COUNT(CUSTOMER_ID), PURCHASE_FREQUENCY_DAYS FROM customer_behaviour_DATA
WHERE PURCHASE_FREQUENCY_DAYS = 365
GROUP BY PURCHASE_FREQUENCY_DAYS;

SELECT 100*((SELECT COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA WHERE PURCHASE_FREQUENCY_DAYS = 365)/COUNT(*)) AS CUSTOMER_RETENTION_RATE
FROM customer_behaviour_DATA;


-- Q8. What are the top 3 most purchased products within each category?

WITH Category_segment AS (
SELECT CATEGORY, ITEM_PURCHASED, count(customer_id),
ROW_NUMBER() OVER(partition by CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEM_RANK
FROM customer_behaviour_DATA
GROUP BY CATEGORY, ITEM_PURCHASED
)

SELECT CATEGORY, ITEM_PURCHASED, ITEM_RANK
FROM CATEGORY_SEGMENT
WHERE ITEM_RANK <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SUBSCRIPTION_STATUS, COUNT(CUSTOMER_ID)
FROM customer_behaviour_DATA
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS;

-- Q10. What is the revenue contribution of each age group?
SELECT * FROM customer_behaviour_DATA;

SELECT SUM(PURCHASE_AMOUNT), AGE_GROUP
FROM customer_behaviour_DATA
GROUP BY AGE_GROUP
ORDER BY SUM(PURCHASE_AMOUNT) DESC;


Select ITEM_PURCHASED, COUNT(CUSTOMER_ID) FROM customer_behaviour_DATA
WHERE AGE_GROUP IN ('SENIOR','ADULT')
GROUP BY ITEM_PURCHASED
ORDER BY COUNT(CUSTOMER_ID) DESC;


SELECT ITEM_PURCHASED, SUM(PURCHASE_AMOUNT) FROM customer_behaviour_DATA
WHERE ITEM_PURCHASED IN ('JEWELRY','JACKET','HOODIE','BLOUSE','PANTS')
GROUP BY ITEM_PURCHASED
ORDER BY SUM(PURCHASE_AMOUNT) DESC;

-- Q14. Which payment methods are preferred by high-value customers?

WITH customer_spend AS (
    SELECT
        customer_id,
        SUM(purchase_amount) AS total_spend
    FROM customer_behaviour_data
    GROUP BY customer_id
),
high_value_customers AS (
    SELECT customer_id
    FROM customer_spend
    WHERE total_spend >
          (SELECT AVG(total_spend) FROM customer_spend)
)
SELECT
    payment_method,
    COUNT(DISTINCT cbd.customer_id) AS high_value_customer_count
FROM customer_behaviour_data cbd
JOIN high_value_customers hvc
    ON cbd.customer_id = hvc.customer_id
GROUP BY payment_method
ORDER BY high_value_customer_count DESC;



-- Q15. How does purchase behaviour differ by season?

SELECT * FROM customer_behaviour_DATA;

SELECT avg(PURCHASE_AMOUNT) AS avg_purchase_amount, count(customer_id) AS total_purchases, sum(purchase_amount) AS total_revenue, SEASON 
FROM customer_behaviour_DATA
GROUP BY SEASON
ORDER BY AVG(PURCHASE_AMOUNT) DESC;

SELECT ITEM_PURCHASED, AVG(PURCHASE_AMOUNT)
FROM customer_behaviour_DATA
WHERE SEASON = 'SUMMER'
GROUP BY ITEM_PURCHASED 
ORDER BY AVG(PURCHASE_AMOUNT);

-- Q12. Which product categories have high purchase frequency but low average spend?

SELECT COUNT(CATEGORY) AS purchase_frequency, AVG(PURCHASE_AMOUNT) AS average_spend,  CATEGORY
FROM customer_behaviour_DATA
GROUP BY CATEGORY
ORDER BY purchase_frequency ASC;


-- Q13. Does applying a discount actually increase purchase?
SELECT COUNT(PURCHASE_AMOUNT) AS TOTAL_PURCHASE,SUM(PURCHASE_AMOUNT) AS REVENUE, DISCOUNT_APPLIED
FROM customer_behaviour_DATA
GROUP BY DISCOUNT_APPLIED;

SELECT ITEM_PURCHASED, SEASON, SUM(PURCHASE_AMOUNT)
FROM customer_behaviour_DATA
WHERE DISCOUNT_APPLIED = 'YES'
GROUP BY ITEM_PURCHASED, SEASON
ORDER BY SUM(PURCHASE_AMOUNT) ASC
LIMIT 5;

-- I want to find items that are purchased less even when discount applied but season wise
WITH ITEM_TOTALS AS(
SELECT ITEM_PURCHASED, DISCOUNT_APPLIED,season, SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASE
FROM customer_behaviour_DATA
WHERE DISCOUNT_APPLIED = 'YES'
GROUP BY ITEM_PURCHASED, DISCOUNT_APPLIED, SEASON
),
RANKED_ITEMS AS (
    SELECT
        ITEM_PURCHASED,
        SEASON,
        TOTAL_PURCHASE,
        RANK() OVER (
            PARTITION BY SEASON
            ORDER BY TOTAL_PURCHASE ASC
        ) AS SEASON_WISE_RANK
    FROM ITEM_TOTALS
)


SELECT ITEM_PURCHASED, SEASON, TOTAL_PURCHASE
FROM RANKED_ITEMS
WHERE SEASON_WISE_RANK <= 3;




-- Q11. Which locations generate the highest revenue per customer (average revenue per customer)?
WITH customer_location_spend AS (
    SELECT
        location,
        customer_id,
        SUM(purchase_amount) AS total_spend
    FROM customer_behaviour_data
    GROUP BY location, customer_id
)
SELECT
    location,
    AVG(total_spend) AS avg_revenue_per_customer
FROM customer_location_spend
GROUP BY location
ORDER BY avg_revenue_per_customer DESC;


WITH location_item_purchases AS (
    SELECT
        location,
        item_purchased,
        COUNT(*) AS total_purchases
    FROM customer_behaviour_data
    GROUP BY location, item_purchased
),
ranked_items AS (
    SELECT
        location,
        item_purchased,
        total_purchases,
        RANK() OVER (
            PARTITION BY location
            ORDER BY total_purchases DESC
        ) AS item_rank
    FROM location_item_purchases
)
SELECT
    location,
    item_purchased,
    total_purchases
FROM ranked_items
WHERE item_rank <= 3 AND LOCATION IN ('WISCONSIN','FLORIDA','MARYLAND','KENTUCKY','DELAWARE','KANSAS','CONNECTICUT')
ORDER BY location, item_rank;


-- Reccomendation : Use location-based coupons (first-order discount, free delivery) for low-performing regions.
